const scripts = {
  Adlm: "Adlam",
  Adlam: "Adlam",
  Ahom: "Ahom",
  Ahom: "Ahom",
  Hluw: "Anatolian Hieroglyphs",
  Anatolian_Hieroglyphs: "Anatolian Hieroglyphs",
  Arab: "Arabic",
  Arabic: "Arabic",
  Armn: "Armenian",
  Armenian: "Armenian",
  Avst: "Avestan",
  Avestan: "Avestan",
  Bali: "Balinese",
  Balinese: "Balinese",
  Bamu: "Bamum",
  Bamum: "Bamum",
  Bass: "Bassa Vah",
  Bassa_Vah: "Bassa Vah",
  Batk: "Batak",
  Batak: "Batak",
  Beng: "Bengali",
  Bengali: "Bengali",
  Bhks: "Bhaiksuki",
  Bhaiksuki: "Bhaiksuki",
  Bopo: "Bopomofo",
  Bopomofo: "Bopomofo",
  Brah: "Brahmi",
  Brahmi: "Brahmi",
  Brai: "Braille",
  Braille: "Braille",
  Bugi: "Buginese",
  Buginese: "Buginese",
  Buhd: "Buhid",
  Buhid: "Buhid",
  Cans: "Canadian Aboriginal",
  Canadian_Aboriginal: "Canadian Aboriginal",
  Cari: "Carian",
  Carian: "Carian",
  Aghb: "Caucasian Albanian",
  Caucasian_Albanian: "Caucasian Albanian",
  Cakm: "Chakma",
  Chakma: "Chakma",
  Cher: "Cherokee",
  Cherokee: "Cherokee",
  Zyyy: "Common",
  Common: "Common",
  Copt: "Coptic",
  Coptic: "Coptic",
  Qaac: "Coptic",
  Coptic: "Coptic",
  Xsux: "Cuneiform",
  Cuneiform: "Cuneiform",
  Cprt: "Cypriot",
  Cypriot: "Cypriot",
  Cyrl: "Cyrillic",
  Cyrillic: "Cyrillic",
  Dsrt: "Deseret",
  Deseret: "Deseret",
  Deva: "Devanagari",
  Devanagari: "Devanagari",
  Dupl: "Duployan",
  Duployan: "Duployan",
  Egyp: "Egyptian Hieroglyphs",
  Egyptian_Hieroglyphs: "Egyptian Hieroglyphs",
  Elba: "Elbasan",
  Elbasan: "Elbasan",
  Ethi: "Ethiopic",
  Ethiopic: "Ethiopic",
  Geor: "Georgian",
  Georgian: "Georgian",
  Glag: "Glagolitic",
  Glagolitic: "Glagolitic",
  Goth: "Gothic",
  Gothic: "Gothic",
  Gran: "Grantha",
  Grantha: "Grantha",
  Grek: "Greek",
  Greek: "Greek",
  Gujr: "Gujarati",
  Gujarati: "Gujarati",
  Guru: "Gurmukhi",
  Gurmukhi: "Gurmukhi",
  Hani: "Han",
  Han: "Han",
  Hang: "Hangul",
  Hangul: "Hangul",
  Hano: "Hanunoo",
  Hanunoo: "Hanunoo",
  Hatr: "Hatran",
  Hatran: "Hatran",
  Hebr: "Hebrew",
  Hebrew: "Hebrew",
  Hira: "Hiragana",
  Hiragana: "Hiragana",
  Armi: "Imperial Aramaic",
  Imperial_Aramaic: "Imperial Aramaic",
  Zinh: "Inherited",
  Inherited: "Inherited",
  Qaai: "Inherited",
  Inherited: "Inherited",
  Phli: "Inscriptional Pahlavi",
  Inscriptional_Pahlavi: "Inscriptional Pahlavi",
  Prti: "Inscriptional Parthian",
  Inscriptional_Parthian: "Inscriptional Parthian",
  Java: "Javanese",
  Javanese: "Javanese",
  Kthi: "Kaithi",
  Kaithi: "Kaithi",
  Knda: "Kannada",
  Kannada: "Kannada",
  Kana: "Katakana",
  Katakana: "Katakana",
  Kali: "Kayah Li",
  Kayah_Li: "Kayah Li",
  Khar: "Kharoshthi",
  Kharoshthi: "Kharoshthi",
  Khmr: "Khmer",
  Khmer: "Khmer",
  Khoj: "Khojki",
  Khojki: "Khojki",
  Sind: "Khudawadi",
  Khudawadi: "Khudawadi",
  Laoo: "Lao",
  Lao: "Lao",
  Latn: "Latin",
  Latin: "Latin",
  Lepc: "Lepcha",
  Lepcha: "Lepcha",
  Limb: "Limbu",
  Limbu: "Limbu",
  Lina: "Linear A",
  Linear_A: "Linear A",
  Linb: "Linear B",
  Linear_B: "Linear B",
  Lisu: "Lisu",
  Lisu: "Lisu",
  Lyci: "Lycian",
  Lycian: "Lycian",
  Lydi: "Lydian",
  Lydian: "Lydian",
  Mahj: "Mahajani",
  Mahajani: "Mahajani",
  Mlym: "Malayalam",
  Malayalam: "Malayalam",
  Mand: "Mandaic",
  Mandaic: "Mandaic",
  Mani: "Manichaean",
  Manichaean: "Manichaean",
  Marc: "Marchen",
  Marchen: "Marchen",
  Gonm: "Masaram Gondi",
  Masaram_Gondi: "Masaram Gondi",
  Mtei: "Meetei Mayek",
  Meetei_Mayek: "Meetei Mayek",
  Mend: "Mende Kikakui",
  Mende_Kikakui: "Mende Kikakui",
  Merc: "Meroitic Cursive",
  Meroitic_Cursive: "Meroitic Cursive",
  Mero: "Meroitic Hieroglyphs",
  Meroitic_Hieroglyphs: "Meroitic Hieroglyphs",
  Plrd: "Miao",
  Miao: "Miao",
  Modi: "Modi",
  Modi: "Modi",
  Mong: "Mongolian",
  Mongolian: "Mongolian",
  Mroo: "Mro",
  Mro: "Mro",
  Mult: "Multani",
  Multani: "Multani",
  Mymr: "Myanmar",
  Myanmar: "Myanmar",
  Nbat: "Nabataean",
  Nabataean: "Nabataean",
  Talu: "New Tai Lue",
  New_Tai_Lue: "New Tai Lue",
  Newa: "Newa",
  Newa: "Newa",
  Nkoo: "Nko",
  Nko: "Nko",
  Nshu: "Nushu",
  Nushu: "Nushu",
  Ogam: "Ogham",
  Ogham: "Ogham",
  Olck: "Ol Chiki",
  Ol_Chiki: "Ol Chiki",
  Hung: "Old Hungarian",
  Old_Hungarian: "Old Hungarian",
  Ital: "Old Italic",
  Old_Italic: "Old Italic",
  Norb: "Old North Arabian",
  Old_North_Arabian: "Old North Arabian",
  Perm: "Old Permic",
  Old_Permic: "Old Permic",
  Xpeo: "Old Persian",
  Old_Persian: "Old Persian",
  Sarb: "Old South Arabian",
  Old_South_Arabian: "Old South Arabian",
  Orkh: "Old Turkic",
  Old_Turkic: "Old Turkic",
  Orya: "Oriya",
  Oriya: "Oriya",
  Osge: "Osage",
  Osage: "Osage",
  Osma: "Osmanya",
  Osmanya: "Osmanya",
  Hmng: "Pahawh Hmong",
  Pahawh_Hmong: "Pahawh Hmong",
  Palm: "Palmyrene",
  Palmyrene: "Palmyrene",
  Pauc: "Pau Cin Hau",
  Pau_Cin_Hau: "Pau Cin Hau",
  Phag: "Phags Pa",
  Phags_Pa: "Phags Pa",
  Phnx: "Phoenician",
  Phoenician: "Phoenician",
  Phlp: "Psalter Pahlavi",
  Psalter_Pahlavi: "Psalter Pahlavi",
  Rjng: "Rejang",
  Rejang: "Rejang",
  Runr: "Runic",
  Runic: "Runic",
  Samr: "Samaritan",
  Samaritan: "Samaritan",
  Saur: "Saurashtra",
  Saurashtra: "Saurashtra",
  Shrd: "Sharada",
  Sharada: "Sharada",
  Shaw: "Shavian",
  Shavian: "Shavian",
  Sidd: "Siddham",
  Siddham: "Siddham",
  Sgnw: "SignWriting",
  SignWriting: "SignWriting",
  Sinh: "Sinhala",
  Sinhala: "Sinhala",
  Sora: "Sora Sompeng",
  Sora_Sompeng: "Sora Sompeng",
  Soyo: "Soyombo",
  Soyombo: "Soyombo",
  Sund: "Sundanese",
  Sundanese: "Sundanese",
  Sylo: "Syloti Nagri",
  Syloti_Nagri: "Syloti Nagri",
  Syrc: "Syriac",
  Syriac: "Syriac",
  Tglg: "Tagalog",
  Tagalog: "Tagalog",
  Tagb: "Tagbanwa",
  Tagbanwa: "Tagbanwa",
  Tale: "Tai Le",
  Tai_Le: "Tai Le",
  Lana: "Thai Tham",
  Tai_Tham: "Thai Tham",
  Tavt: "Tia Viet",
  Tai_Viet: "Tia Viet",
  Takr: "Takri",
  Takri: "Takri",
  Taml: "Tamil",
  Tamil: "Tamil",
  Tang: "Tangut",
  Tangut: "Tangut",
  Telu: "Telugu",
  Telugu: "Telugu",
  Thaa: "Thaana",
  Thaana: "Thaana",
  Thai: "Thai",
  Thai: "Thai",
  Tibt: "Tibetan",
  Tibetan: "Tibetan",
  Tfng: "Tifinagh",
  Tifinagh: "Tifinagh",
  Tirh: "Tirhuta",
  Tirhuta: "Tirhuta",
  Ugar: "Ugaritic",
  Ugaritic: "Ugaritic",
  Vaii: "Vai",
  Vai: "Vai",
  Wara: "Warang Citi",
  Warang_Citi: "Warang Citi",
  Yiii: "Yi",
  Yi: "Yi",
  Zanb: "Zanzabar Square",
  Zanzabar_Square: "Zanzabar Square",
};

module.exports = { scripts }